# Generated by Django 5.2.1 on 2025-05-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа')),
                ('serial_number_mask', models.CharField(max_length=255, verbose_name='Маска серийного номера')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено (мягкое удаление)')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('equipment_type', 'serial_number'), name='unique_equipment_type_serial_number_if_not_deleted')],
            },
        ),
    ]
